spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
  profiles:
    default: development


rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://b9440c518a46d605bac1f3a02458802e@o4507593506750464.ingest.de.sentry.io/4507593511927888
  traces-sample-rate: 1.0

